export const viLabels = {
    singleBag: 'Túi đơn',
    doubleBag: 'Túi đôi',
    versatileBag: 'Túi đa dạng',
    mergedOrder: 'Đơn ghép',
    box: 'Chọn thùng',
    checkout: 'Thanh toán',
    order: 'Đặt Hàng',
    copy: 'Sao Chép',
    copied: 'Đã sao chép',
    processing: 'Đang xử lý',
    confirm: 'Xác nhận',
    confirmPayment: 'XÁC NHẬN THANH TOÁN',
    customerInfo: 'Thông tin đặt hàng',
    orderInfo: 'Thông tin đơn hàng',
    orderConfirmation: 'Xác nhận đơn hàng',
    orderCode: 'Mã đơn hàng',
    orderDetail: 'Chi tiết đơn hàng',
    invoice: 'Hóa đơn',
    invoiceDetail: 'Hóa đơn chi tiết',
    loadDataError: 'Không thể tải dữ liệu',
    genericError: 'Có lỗi xảy ra',
    invalidTotal: 'Tổng tiền không hợp lệ',
    cancel: 'Hủy',
} as const;

export const viRegex = {
    singleBag: /Túi\s+[Đđ]ơn|Tui\s+Don/i,
    doubleBag: /Túi\s+[Đđ]ôi|Tui\s+Doi/i,
    versatileBag: /Túi\s+[Đđ]a\s+Dạng|Túi\s+[Đđ]a\s+dạng|Tui\s+Da\s+Dang/i,
    mergedOrder: /[Đđ]ơn\s+ghép|Don\s+ghep/i,
    box: /Chọn\s+thùng|Chon\s+Thung/i,
    checkout: /Thanh\s+toán|Thanh\s+toan/i,
    order: /[Đđ]ặt\s+Hàng|[Đđ]ặt\s+hàng|Dat\s+Hang/i,
    copy: /Sao\s+Chép|Sao\s+chép|Sao\s+Chep/i,
    copied: /[Đđ]ã\s+sao\s+chép|Da\s+sao\s+chep|Copied/i,
    processing: /[Đđ]ang\s+xử\s+lý|Dang\s+xu\s+ly|Processing|loading|[Đđ]ang\s+tải|Dang\s+tai/i,
    confirm: /Xác\s+nhận|Xac\s+nhan/i,
    confirmPayment: /XÁC\s+NHẬN\s+THANH\s+TOÁN|Xác\s+nhận\s+thanh\s+toán|Xac\s+nhan\s+thanh\s+toan/i,
    customerInfo: /Thông\s+tin\s+đặt\s+hàng|Thong\s+tin\s+dat\s+hang/i,
    orderInfo: /Thông\s+tin\s+đơn\s+hàng|Thong\s+tin\s+don\s+hang/i,
    orderConfirmation: /Xác\s+nhận\s+đơn\s+hàng|Xac\s+nhan\s+don\s+hang/i,
    orderCode: /Mã\s+đơn\s+hàng|Ma\s+don\s+hang/i,
    orderDetail: /Chi\s+tiết\s+đơn\s+hàng|Chi\s+tiet\s+don\s+hang/i,
    invoice: /Hóa\s+đơn|Hoá\s+đơn|Hoa\s+don/i,
    invoiceDetail: /Hóa\s+đơn\s+chi\s+tiết|Hoá\s+đơn\s+chi\s+tiết|Hoa\s+don\s+chi\s+tiet/i,
    printInvoiceDetail: /In\s+(?:hóa|hoá|hoa)\s+đơn\s+chi\s+tiết|In\s+hoa\s+don\s+chi\s+tiet/i,
    loadDataError: /Không\s+thể\s+tải\s+dữ\s+liệu|Khong\s+the\s+tai\s+du\s+lieu/i,
    genericError: /Có\s+lỗi\s+xảy\s+ra|Co\s+loi\s+xay\s+ra/i,
    invalidTotal: /Tổng\s+tiền\s+không\s+hợp\s+lệ|Tong\s+tien\s+khong\s+hop\s+le/i,
    customerNamePlaceholder: /Nhập\s+tên\s+người\s+đặt\s+hàng|Nhập\s+tên\s+người\s+nhận\s+quà/i,
    phonePlaceholder: /Nhập\s+số\s+điện\s+thoại|Nhập\s+SĐT\s+người\s+nhận\s+quà/i,
} as const;

export function textRegexSelector(pattern: RegExp) {
    return `text=${pattern.toString()}`;
}
